baseURL = "https://saksham.khanal.github.io/"
title = "Saksham Khanal"
theme = "hugo-coder"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true

[pagination]
  pagerSize = 10 

[params]
  author = "Saksham Khanal"
  description = "Just a curious dev navigating the force."
  keywords = "blog,developer,personal,portfolio"
  info = "Software Engineer | Zen Coder | Star Wars Fan"
  avatarURL = "images/avatar.png" # Optional: put your profile pic in static/images/
  dateFormat = "2006-01-02"
  since = 2024
  colorScheme = "auto" # options: auto, light, dark

# Optional: add your GitHub/LinkedIn
[[params.social]]
  name = "GitHub"
  icon = "fa fa-github"
  weight = 1
  url = "https://github.com/Sakshamkhanal"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin"
  weight = 2
  url = "https://www.linkedin.com/in/saksham-khanal-0a5754256/"

[markup.highlight]
  style = "monokai"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

# Deployment tweaks
[deployment]
  [[deployment.targets]]
    name = "github"
    URL = "git@github.com:your-username/your-repo.git"
